name: Build and tests

on: 
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Build package
        run: |
            python -m pip install --upgrade pip
            pip install wheel
            python setup.py bdist_wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/qoi_compress-*.whl
          name: whl_artifact

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: whl_artifact
      - name: Install package
        run: pip3 install qoi_compress-*.whl
      - name: Run tests
        run: python -m unittest discover -s tests

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install mypy
        run: |
          pip3 install --upgrade pip
          pip3 install mypy
          pip3 install numpy
      - name: Run mypy tests
        run: mypy src
